apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-sc
  name: pod-sc
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
  containers:
  - command:
    - sh
    - -c
    - sleep 1d
    image: busybox:1.34
    name: sh
